apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask
  template:
    metadata:
      name: flask
      labels:
        name: flask
    spec:
      containers:
        - name: flask
          image: hello-fresh:buildnumber
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"
