apiVersion: v1
kind: Service
metadata:
  labels:
    name: flask
  name: flask-svc
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: flask
  type: ClusterIP
