apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /configs
        backend:
          serviceName: flask-svc
          servicePort: 8080
      - path: /search
        backend:
          serviceName: flask-svc
          servicePort: 8080
