metadata:
  name: flask-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host:
      http:
        paths:
          - path: /configs
            pathType: Prefix
            backend:
              service:
                name: flask-svc
                port:
                  number: 8080
          - path: /search
            pathType: Prefix
            backend:
              service:
                name: flask-svc
                port:
                  number: 8080
